# app deployment file
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab
  labels:
    app: lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lab
  template:
    metadata:
      labels:
        app: lab
    spec:
      containers:
        - name: lab
          # merkoadelina dockerhub username , fti repo
          image: merkoadelina/fti:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: logs-volume
              mountPath: /var/logs
      volumes:
        - name: logs-volume
          hostPath:
            path: /var/logs
            type: DirectoryOrCreate

# kubectl apply -f app-deployment.yaml