# app service file
apiVersion: v1
kind: Service
metadata:
  name: lab-srv1
spec:
  ports:
    - port: 8081
      protocol: TCP
      targetPort: 8080
  selector:
    app: lab
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: lab-srv2
spec:
  type: NodePort
  ports:
    - port: 8082
      protocol: TCP
      targetPort: 8080
  selector:
    app: lab

# kubectl apply -f app-service.yaml
